server:
  port: ${PORT:5000}

base-url: /api

rollbar-token: 05b126c7c16a404fb2f14add74dca571

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop